package homebrew

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const legacyPostflightFixture = `  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unbound-force"]
      # Create uf symlink alias for daily-use convenience (FR-002/FR-009).
      system_command "/bin/ln", args: ["-sf", "#{staged_path}/unbound-force", "#{HOMEBREW_PREFIX}/bin/uf"]
    end
  end`

const declarativePostflightFixture = `  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "{{staged_path}}/unbound-force"]
      symlink "unbound-force", "{{HOMEBREW_PREFIX}}/bin/uf", overwrite: true
    end
  end`

// generatedCaskFixture preserves the relevant structure of the v0.18.0
// GoReleaser asset that exposed the indentation mismatch.
const generatedCaskFixture = `# This file was generated by GoReleaser. DO NOT EDIT.
cask "unbound-force" do
  version "0.18.0"

  binary "unbound-force"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unbound-force"]
      # Create uf symlink alias for daily-use convenience (FR-002/FR-009).
      system_command "/bin/ln", args: ["-sf", "#{staged_path}/unbound-force", "#{HOMEBREW_PREFIX}/bin/uf"]
    end
  end

  # No zap stanza required
end
`

func TestRun_ExactSingleHookReplacement(t *testing.T) {
	input := generatedCaskFixture
	want := strings.Replace(generatedCaskFixture, legacyPostflightFixture, declarativePostflightFixture, 1)

	outputPath := runCaskFixture(t, input)
	got, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read transformed Cask: %v", err)
	}
	if string(got) != want {
		t.Errorf("transformed Cask = %q, want %q", got, want)
	}
}

func TestRun_AbsentHookRejectsAndLeavesOutputAbsent(t *testing.T) {
	directory := t.TempDir()
	inputPath := filepath.Join(directory, "input.rb")
	outputPath := filepath.Join(directory, "output.rb")
	if err := os.WriteFile(inputPath, []byte("cask \"unbound-force\" do\nend\n"), 0o644); err != nil {
		t.Fatalf("write input Cask: %v", err)
	}

	_, err := Run(Options{InputPath: inputPath, OutputPath: outputPath})
	if err == nil {
		t.Fatal("Run() error = nil, want missing hook error")
	}
	const wantError = "transform generated Homebrew Cask hook: expected exactly one legacy postflight hook, found 0"
	if err.Error() != wantError {
		t.Errorf("Run() error = %q, want %q", err, wantError)
	}
	if _, err := os.Stat(outputPath); !os.IsNotExist(err) {
		t.Errorf("output file state = %v, want absent output file", err)
	}
}

func TestRun_DuplicateHookRejectsAndLeavesOutputUnchanged(t *testing.T) {
	directory := t.TempDir()
	inputPath := filepath.Join(directory, "input.rb")
	outputPath := filepath.Join(directory, "output.rb")
	input := legacyPostflightFixture + "\n" + legacyPostflightFixture
	if err := os.WriteFile(inputPath, []byte(input), 0o644); err != nil {
		t.Fatalf("write input Cask: %v", err)
	}
	const originalOutput = "existing transformed Cask\n"
	if err := os.WriteFile(outputPath, []byte(originalOutput), 0o644); err != nil {
		t.Fatalf("write existing output Cask: %v", err)
	}

	_, err := Run(Options{InputPath: inputPath, OutputPath: outputPath})
	if err == nil {
		t.Fatal("Run() error = nil, want duplicate hook error")
	}
	const wantError = "transform generated Homebrew Cask hook: expected exactly one legacy postflight hook, found 2"
	if err.Error() != wantError {
		t.Errorf("Run() error = %q, want %q", err, wantError)
	}
	got, readErr := os.ReadFile(outputPath)
	if readErr != nil {
		t.Fatalf("read existing output Cask: %v", readErr)
	}
	if string(got) != originalOutput {
		t.Errorf("output Cask = %q, want unchanged %q", got, originalOutput)
	}
}

func TestRun_NearMatchRejectsAndLeavesOutputAbsent(t *testing.T) {
	directory := t.TempDir()
	inputPath := filepath.Join(directory, "input.rb")
	outputPath := filepath.Join(directory, "output.rb")
	nearMatch := strings.Replace(legacyPostflightFixture, "if OS.mac?", "if OS.mac? # changed", 1)
	if err := os.WriteFile(inputPath, []byte(nearMatch), 0o644); err != nil {
		t.Fatalf("write input Cask: %v", err)
	}

	_, err := Run(Options{InputPath: inputPath, OutputPath: outputPath})
	if err == nil {
		t.Fatal("Run() error = nil, want near-match hook error")
	}
	const wantError = "transform generated Homebrew Cask hook: expected exactly one legacy postflight hook, found 0"
	if err.Error() != wantError {
		t.Errorf("Run() error = %q, want %q", err, wantError)
	}
	if _, err := os.Stat(outputPath); !os.IsNotExist(err) {
		t.Errorf("output file state = %v, want absent output file", err)
	}
}

func TestRun_WriteFailureLeavesOutputUnchanged(t *testing.T) {
	directory := t.TempDir()
	inputPath := filepath.Join(directory, "input.rb")
	outputPath := filepath.Join(directory, "output.rb")
	if err := os.WriteFile(inputPath, []byte(legacyPostflightFixture), 0o644); err != nil {
		t.Fatalf("write input Cask: %v", err)
	}
	const originalOutput = "existing transformed Cask\n"
	if err := os.WriteFile(outputPath, []byte(originalOutput), 0o644); err != nil {
		t.Fatalf("write existing output Cask: %v", err)
	}

	_, err := Run(Options{
		InputPath:  inputPath,
		OutputPath: outputPath,
		WriteFile: func(path string, content []byte, permission os.FileMode) error {
			if err := os.WriteFile(path, content[:len(content)/2], permission); err != nil {
				return err
			}
			return errors.New("simulated disk full")
		},
	})
	if err == nil {
		t.Fatal("Run() error = nil, want write failure")
	}
	const wantError = "write transformed Homebrew Cask: simulated disk full"
	if err.Error() != wantError {
		t.Errorf("Run() error = %q, want %q", err, wantError)
	}
	got, readErr := os.ReadFile(outputPath)
	if readErr != nil {
		t.Fatalf("read existing output Cask: %v", readErr)
	}
	if string(got) != originalOutput {
		t.Errorf("output Cask = %q, want unchanged %q", got, originalOutput)
	}
	entries, readErr := os.ReadDir(directory)
	if readErr != nil {
		t.Fatalf("read Cask directory: %v", readErr)
	}
	if len(entries) != 2 {
		t.Errorf("Cask directory entries = %d, want 2 without partial output", len(entries))
	}
}

func TestRun_PreservesSurroundingContent(t *testing.T) {
	const prefix = "# generated by GoReleaser\nclass UnboundForce < Cask\n"
	const suffix = "\n  homepage \"https://github.com/unbound-force/unbound-force\"\nend\n"
	input := prefix + legacyPostflightFixture + suffix
	want := prefix + declarativePostflightFixture + suffix

	outputPath := runCaskFixture(t, input)
	got, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read transformed Cask: %v", err)
	}
	if string(got) != want {
		t.Errorf("transformed Cask = %q, want %q", got, want)
	}
}

func runCaskFixture(t *testing.T, input string) string {
	t.Helper()
	directory := t.TempDir()
	inputPath := filepath.Join(directory, "input.rb")
	outputPath := filepath.Join(directory, "output.rb")
	if err := os.WriteFile(inputPath, []byte(input), 0o644); err != nil {
		t.Fatalf("write input Cask: %v", err)
	}
	result, err := Run(Options{InputPath: inputPath, OutputPath: outputPath})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if result.OutputPath != outputPath {
		t.Fatalf("Run() output path = %q, want %q", result.OutputPath, outputPath)
	}
	return outputPath
}
